# job tab used to generate tile labels
input_label_tag: ov_default_labels
#
# job tag for the inference
job_tag: infer_ov_clf

# pixel width/height of slide tiles (size of patches)
tile_size: 128

# desired downscale factor
scale_factor: 16

# desired magnification
magnification: 20

model_package: luna.pathology.models.eng_tissuenet

checkpoint_path: ../PRO_12-123/model/outputs/ckpts/ckpt_8.pt

# path to model and output checkpoints
# model:
   # number of classification groups for model
   n_classes: 7

# path to output directory 
root_path: ../PRO_12-123/tables/tiles
